### ISSUE TITLE
Pixelfix no longer working

### ISSUE THREAD

**Issue by ZacBytes** [Corecii/Transparent-Pixel-Fix#1]
Previously:
![image](https://user-images.githubusercontent.com/18497727/69301193-65058900-0c50-11ea-9960-77f87ce6fce1.png)

Now:
![image](https://user-images.githubusercontent.com/18497727/69301202-69ca3d00-0c50-11ea-9979-e6069a36a721.png)

This started happening yesterday. The image background should be pink if it's fixed but now they are black. There is no error when I use sendTo pixelfix but it's no longer fixing fuzzy outlines :/

**Comment by Corecii** [comment]
This is caused by changes Roblox makes to images on upload. This is a re-occurrance of the following bug report:

https://devforum.roblox.com/t/uploading-a-decal-converts-the-color-of-all-transparent-pixels-to-black/348995

I will close this issue once Roblox has fixed this on their end.

**Comment by Corecii** [comment]
This has been fixed 👍 

https://devforum.roblox.com/t/uploading-a-decal-converts-the-color-of-all-transparent-pixels-to-black/348995/8
